---
version: '3'
services:
  ldapserver:
    image: osixia/openldap:1.3.0
    hostname: ldapserver
    container_name: ldapserver
    environment: 
      LDAP_ORGANISATION: "Confluent Inc."
      LDAP_DOMAIN: "confluent.test"
      LDAP_ADMIN_PASSWORD: "password"
    ports:
      - "7389:389"
      - "7636:636"
    volumes:
      - $PWD/data/ldap-seed.ldif:/container/service/slapd/assets/config/bootstrap/ldif/custom/50-bootstrap.ldif
    command: >
      --loglevel debug
      --copy-service

  ldapgui:
    image: osixia/phpldapadmin
    depends_on: 
      - ldapserver
    container_name: ldapgui
    environment: 
      PHPLDAPADMIN_LDAP_HOSTS: ldapserver
    ports:
      - "7443:443"
